const theme = {
  colors: {
    bgPrimary: '#0D1117',
    bgSecondary: '#161B22',
    bgCard: '#161B22',
    bgCardHover: '#1C2333',
    bgInput: '#0D1117',
    bgNavbar: '#0D1117ee',
    accent: '#00E676',
    accentDark: '#00C853',
    accentLight: '#69F0AE',
    textPrimary: '#FFFFFF',
    textSecondary: '#8B949E',
    textMuted: '#9AA4B2',
    border: '#21262D',
    borderLight: '#30363D',
    danger: '#FF5252',
    dangerDark: '#D32F2F',
    warning: '#FFD740',
    warningDark: '#FFC107',
    success: '#00E676',
    info: '#40C4FF',
    overlay: 'rgba(0, 0, 0, 0.6)',
  },
  shadows: {
    card: '0 2px 8px rgba(0, 0, 0, 0.3)',
    cardHover: '0 4px 16px rgba(0, 230, 118, 0.15)',
    button: '0 2px 8px rgba(0, 230, 118, 0.3)',
    navbar: '0 2px 12px rgba(0, 0, 0, 0.5)',
    input: '0 0 0 2px rgba(0, 230, 118, 0.2)',
  },
  borderRadius: {
    sm: '8px',
    md: '12px',
    lg: '16px',
    xl: '24px',
    full: '50%',
  },
  spacing: {
    xs: '4px',
    sm: '8px',
    md: '16px',
    lg: '24px',
    xl: '32px',
    xxl: '48px',
  },
  fontSize: {
    xs: '11px',
    sm: '13px',
    md: '15px',
    lg: '18px',
    xl: '22px',
    xxl: '28px',
    hero: '36px',
  },
  fontWeight: {
    normal: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    extrabold: 800,
  },
  transitions: {
    fast: 'all 0.15s ease',
    normal: 'all 0.25s ease',
    slow: 'all 0.4s ease',
  },
  breakpoints: {
    mobile: '480px',
    tablet: '768px',
    desktop: '1024px',
    wide: '1280px',
  },
  zIndex: {
    dropdown: 100,
    sticky: 200,
    fixed: 300,
    modalBackdrop: 400,
    modal: 500,
    toast: 600,
  },
};

export default theme;

export const commonStyles = {
  pageContainer: {
    minHeight: '100vh',
    backgroundColor: theme.colors.bgPrimary,
    color: theme.colors.textPrimary,
    fontFamily: "'Inter', sans-serif",
  },
  card: {
    backgroundColor: theme.colors.bgCard,
    borderRadius: theme.borderRadius.md,
    border: `1px solid ${theme.colors.border}`,
    padding: theme.spacing.lg,
    transition: theme.transitions.normal,
  },
  cardHover: {
    backgroundColor: theme.colors.bgCardHover,
    boxShadow: theme.shadows.cardHover,
    transform: 'translateY(-2px)',
  },
  button: {
    backgroundColor: theme.colors.accent,
    color: '#000',
    border: 'none',
    borderRadius: theme.borderRadius.xl,
    padding: `${theme.spacing.sm} ${theme.spacing.lg}`,
    fontSize: theme.fontSize.md,
    fontWeight: theme.fontWeight.semibold,
    cursor: 'pointer',
    transition: theme.transitions.fast,
    fontFamily: "'Inter', sans-serif",
  },
  buttonOutline: {
    backgroundColor: 'transparent',
    color: theme.colors.accent,
    border: `2px solid ${theme.colors.accent}`,
    borderRadius: theme.borderRadius.xl,
    padding: `${theme.spacing.sm} ${theme.spacing.lg}`,
    fontSize: theme.fontSize.md,
    fontWeight: theme.fontWeight.semibold,
    cursor: 'pointer',
    transition: theme.transitions.fast,
    fontFamily: "'Inter', sans-serif",
  },
  input: {
    backgroundColor: theme.colors.bgInput,
    color: theme.colors.textPrimary,
    border: `1px solid ${theme.colors.border}`,
    borderRadius: theme.borderRadius.sm,
    padding: `${theme.spacing.sm} ${theme.spacing.md}`,
    fontSize: theme.fontSize.md,
    width: '100%',
    outline: 'none',
    transition: theme.transitions.fast,
    fontFamily: "'Inter', sans-serif",
  },
  inputFocus: {
    borderColor: theme.colors.accent,
    boxShadow: theme.shadows.input,
  },
  sectionTitle: {
    fontSize: theme.fontSize.lg,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textPrimary,
    marginBottom: theme.spacing.md,
  },
  subtitle: {
    fontSize: theme.fontSize.sm,
    color: theme.colors.textSecondary,
  },
};

export const mediaQueries = {
  mobile: `@media (max-width: ${theme.breakpoints.tablet})`,
  tablet: `@media (min-width: ${theme.breakpoints.tablet}) and (max-width: ${theme.breakpoints.desktop})`,
  desktop: `@media (min-width: ${theme.breakpoints.desktop})`,
};
